#!/usr/bin/env bash

#######################################
#  __  .__                            #
#_/  |_|  |__   ____   _____   ____   #
#\   __\  |  \_/ __ \ /     \_/ __ \  #
# |  | |   Y  \  ___/|  Y Y  \  ___/  #
# |__| |___|  /\___  >__|_|  /\___  > #
#           \/     \/      \/     \/  #
#######################################
hc() {
    herbstclient "$@"
}

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc attr theme.padding_left 30
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#FFFFFF'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 32

hc attr theme.normal.color '#4a4d49'
hc attr theme.active.color '#d5d3c7'
hc attr theme.urgent.color orange
hc attr theme.inner_width 18
hc attr theme.outer_width 0
hc attr theme.inner_color '#aeaca2'
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.normal.inner_color '#373a36'
hc attr theme.active.outer_color '#000000'
hc attr theme.background_color '#141414'
hc attr theme.inner_width 8

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

feh --bg-fill ~/Pictures/Wallpapers/moon.jpg

