#!/usr/bin/env bash

#######################################
#  __  .__                            #
#_/  |_|  |__   ____   _____   ____   #
#\   __\  |  \_/ __ \ /     \_/ __ \  #
# |  | |   Y  \  ___/|  Y Y  \  ___/  #
# |__| |___|  /\___  >__|_|  /\___  > #
#           \/     \/      \/     \/  #
#######################################
hc() {
    herbstclient "$@"
}

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set hide_covered_windows 0

hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc set window_gap 0

hc set frame_border_active_color '#ffffff'
hc set frame_border_normal_color '#ffffff'
hc set frame_border_width 0
hc set frame_bg_active_color '#ffffff'
hc set frame_bg_normal_color '#ffffff'
hc set frame_active_opacity 100
hc set frame_normal_opacity 0

hc attr theme.inner_width 0
hc attr theme.outer_width 0
hc attr theme.border_width 0
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.active.color '#517f8d'
hc attr theme.normal.color '#002535'

hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc attr theme.padding_left 12
hc attr theme.padding_top 12

hc attr theme.padding_right 1
hc attr theme.padding_bottom 1

#feh --randomize --bg-fill ~/Pictures/Wallpapers/pa


