#!/usr/bin/env bash

# You can call this script like this:
# $ ./vol up
# $ ./vol down

# Script inspired by these wonderful people:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a

function get_brightness {
  light -G | cut -d '.' -f 1
}




function send_notification {
  brightness=$(get_brightness)
  # Make the bar with the special character ─ (it's not dash -)
  # https://en.wikipedia.org/wiki/Box-drawing_character
  bar=$(seq -s "━" $(($brightness / 3)) | sed 's/[0-9]//g')
  dunstify -i "~/bin/notes"   -r 2594 -u low "🔆$brightness%	$bar" -a volume
  # Send the notification
}

case $1 in
  up)
    # increase the backlight by 5%
    light -A 2
    send_notification
    ;;
  down)
    # decrease the backlight by 5%
    light -U 2
    send_notification
    ;;
esac



