#!/usr/bin/env bash
#
#   Script used to change volume level.
#   Script is bound to function volume keys by i3 in its configuration file.
#   
#   REQUIRES: pactl, lemonbar (popup alias)
#################################################################################

volume_step=5

function send_notify(){
   # while [[ $(pgrep lemonbar) != "" ]]; do
#	killall --younger-than $"{date +"%Ih %Mm %Ss"}" lemonbar
 #   done

    cur_vol=$(get_current_volume)
    if [[ $(speaker_status) == "off" ]]; then
        vol_text="%{c}%{T2}\uf026%{T1}  "
        for block in $(seq 0 19); do
            let math_blk=$block*${volume_step}
            vol_text="${vol_text}\u25AB"
        done
    else
        vol_text="%{c}%{T2}\uf028%{T1}  " # Add volume icon
        for block in $(seq 0 19); do
            let math_blk=$block*${volume_step}
            if [[ $math_blk -lt $cur_vol ]]; then
                vol_text="${vol_text}\u25AA"    # Filled small square
            else
                vol_text="${vol_text}\u25AB"    # Empty small square
            fi
        done        
    fi
    popup "${vol_text} ${cur_vol}"
}

function get_current_volume(){
    pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) |\
    tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

function speaker_status(){
    amixer get Master | grep "Mono:" | tr -s ' ' ';' | cut -f 7 -d ';' |\
    tr -d '[]'
}

if [[ $1 == 1 && $(get_current_volume) -lt 100 ]]; then
    pactl list short sinks | cut -f1 | while read -r line; do pactl set-sink-volume $line +${volume_step}%; done
elif [[ $1 == 0 ]]; then
    pactl list short sinks | cut -f1 | while read -r line; do pactl set-sink-volume $line -${volume_step}%; done
elif [[ $1 == -1 ]]; then
    pactl list short sinks | cut -f1 | while read -r line; do pactl set-sink-mute $line toggle; done
fi

send_notify
