#!/usr/bin/env bash
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
#									    #
# $$\                           $$\       $$\                 $$\           #
# $$ |                          $$ |      \__|                $$ |          #
# $$ |  $$\  $$$$$$\  $$\   $$\ $$$$$$$\  $$\ $$$$$$$\   $$$$$$$ | $$$$$$$\ #
# $$ | $$  |$$  __$$\ $$ |  $$ |$$  __$$\ $$ |$$  __$$\ $$  __$$ |$$  _____|#
# $$$$$$  / $$$$$$$$ |$$ |  $$ |$$ |  $$ |$$ |$$ |  $$ |$$ /  $$ |\$$$$$$\  #
# $$  _$$<  $$   ____|$$ |  $$ |$$ |  $$ |$$ |$$ |  $$ |$$ |  $$ | \____$$\ #
# $$ | \$$\ \$$$$$$$\ \$$$$$$$ |$$$$$$$  |$$ |$$ |  $$ |\$$$$$$$ |$$$$$$$  |#
# \__|  \__| \_______| \____$$ |\_______/ \__|\__|  \__| \_______|\_______/ #
#                     $$\   $$ |                                            #
#                     \$$$$$$  |                                            #
#                      \______/                                             #
#									    #
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$#
hc() {
    herbstclient "$@"
}
Mod=Mod4

configdir="/home/david/.config/herbstluftwm"
bindir=$configdir/"bin"

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Global operations

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload


# rotations

hc keybind $Mod-y chain . lock . rotate . rotate . rotate . unlock
hc keybind $Mod-Alt-y chain . lock . rotate . rotate . unlock
hc keybind $Mod-Shift-y chain . lock . rotate . unlock


# Death

hc keybind $Mod-x close
hc keybind $Mod-w remove
hc keybind $Mod-Shift-c close_or_remove

# Birth

hc keybind $Mod-d spawn dmenu_run
hc keybind $Mod-equal spawn ~/scripts/dcalc

hc keybind $Mod-Return spawn ${TERMINAL:-termite} # use your $TERMINAL with xterm as fallback
#hc keybind $Mod-Return spawn termite -c ~/.config/termite/snowconf
#hc keybind $Mod-Return spawn termite -c ~/.config/termite/paperconf
#hc keybind $Mod-Return spawn xterm
#hc keybind $Mod-Return spawn termite -c ~/.config/termite/cageconf
hc keybind $Mod-Shift-v spawn firefox

# Volume control
#hc keybind  XF86AudioRaiseVolume spawn amixer set Master -q 1%+
hc keybind  XF86AudioRaiseVolume  spawn /home/david/scripts/vol up
hc keybind  XF86AudioLowerVolume spawn /home/david/scripts/vol down
hc keybind XF86AudioMute spawn /home/david/scripts/vol mute
#!lamixer set Master -q toggle 
#/home/david/scripts/vol mute
hc keybind XF86MonBrightnessUp spawn /home/david/scripts/bright up
hc keybind XF86MonBrightnessDown spawn /home/david/scripts/bright down

# Spotify control
#hc keybind $Mod-Alt-Down spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
hc keybind $Mod-Alt-Down spawn playerctl play-pause 
hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind $Mod-Alt-Left spawn playerctl previous
hc keybind XF86AudioPrev spawn playerctl next
hc keybind $Mod-Alt-Right spawn playerctl next
hc keybind XF86AudioNext spawn playerctl next
#hc keybind $Mod-Alt-Left spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
#hc keybind $Mod-Alt-Right spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next

#screenshots and recording
hc keybind $Mod-Alt-p spawn scrot -e 'mv $f ~/Pictures/screenshots' 

hc keybind $Mod-Shift-p spawn maim -s ~/Pictures/screenshots/$(date +%s).png
bash /home/david/scripts/names.sh
hc keybind $Mod-Shift-f spawn /home/david/scripts/recorder 
hc keybind $Mod-Ctrl-f spawn /home/david/scripts/blaze -p preset
hc keybind $Mod-Alt-f spawn pkill ffmpeg

#Focus
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l focus right

#Shifting
hc keybind $Mod-Shift-h or / shift left / \
    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-j or / shift down / \
    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-k or / shift up / \
    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-l or / shift right / \
chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# Splitting
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5

hc keybind $Mod-bracketleft split vertical 0.333333
hc keybind $Mod-bracketright split horizontal 0.333333
hc keybind $Mod-Shift-bracketleft split vertical 0.666667
hc keybind $Mod-Shift-bracketright split horizontal 0.666667
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode


# Resizing
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# Window Manipulations
hc keybind $Mod-t floating toggle
hc keybind $Mod-Shift-t spawn "$bindir"/floatsingle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# Frame Manipulations
hc keybind $Mod-space                                                             \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1


#Monitor
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind Mod1-Tab cycle
hc keybind $Mod-i jumpto urgent

#Magic
hc keybind $Mod-grave spawn "$bindir"/scratchpad
hc keybind $Mod-s spawn "$bindir"/wselect

#minimize and maximize windows
hc keybind $Mod-m         spawn "$bindir"/minimize +1
hc keybind $Mod-Control-m spawn "$bindir"/minimize  -1
hc keybind $Mod-Shift-m   spawn  "$bindir"/minimize
hc keybind $Mod-Alt-m spawn "$bindir"/minimize 0
hc keybind $Mod-b spawn "$bindir"/maximize


# Mice

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set focus_follows_mouse 1

# multimonitor
hc keybind $Mod-Control-2 spawn /home/david/scripts/2monhome.sh
hc keybind $Mod-Control-0 chain . spawn xrandr --auto . reload

# stupid little scripts
# Broken: hc keybind $Mod-Shift-l spawn /home/david/scripts/locker.sh
hc keybind $Mod-Shift-n spawn networkmanager_dmenu 

hc keybind F1 spawn dmenu_run
hc keybind $Mod-F1 spawn dmenu_run
hc keybind $Mod-a spawn xfce4-appfinder
