#!/usr/bin/env bash
###############################################################################
#       _               _         _   _        __ _                           #
#      | |__   ___ _ __| |__  ___| |_| |_   _ / _| |_ _      _ _ __ ___       #
#      | '_ \ / _ \ '__| '_ \/ __| __| | | | | |_| __| \ /\ / | '_ ` _ \      #
#      | | | |  __/ |  | |_) \__ \ |_| | |_| |  _| |_ \ V  V /| | | | | |     #
#      |_| |_|\___|_|  |_.__/|___/\__|_|\__,_|_|  \__| \_/\_/ |_| |_| |_|     #
#                                                                             #
###############################################################################
# Initialise                                                                {{{
#------------------------------------------------------------------------------
hc() {
    herbstclient "$@"
}
hc emit_hook reload
#Max default
configdir="/home/david/.config/herbstluftwm"
themedir=$configdir/"themes"
paneldir=$configdir/"panels"
#bindir=$configdir/"bin"
# Clear dmenu cache, needed for nixos
rm ~/.cache/dmenu_run

hc lock
#hc spawn $bindir/dialoglistener
#Keybindings
hc keyunbind --all
$configdir/keybinds 

#theming
#$themedir/moontheme
$themedir/cyantime
#$themedir/papertheme
#$themedir/snowtheme
#$themedir/snowtheme


hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
# rules

hc unlock
hc set default_frame_layout 1
hc detect_monitors

# panel
# find the panel
nmon=$(herbstclient list_monitors | wc -l)
#if [ "$nmon" = "1" ]; then
#	 panel=$paneldir/lemonpanel
	panel=$paneldir/dzenpanel
#else
#	panel=$paneldir/dzenpanel
#fi
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
#    monitor=0
    "$panel" "$monitor" &
done


if [ "$nmon" = "2" ]; then
	bash ~/.screenlayout/2monhome.sh
fi
#xset s off -dpms

