#!/usr/bin/env bash
###############################################################################
#       _               _         _   _        __ _                           #
#      | |__   ___ _ __| |__  ___| |_| |_   _ / _| |_ _      _ _ __ ___       #
#      | '_ \ / _ \ '__| '_ \/ __| __| | | | | |_| __| \ /\ / | '_ ` _ \      #
#      | | | |  __/ |  | |_) \__ \ |_| | |_| |  _| |_ \ V  V /| | | | | |     #
#      |_| |_|\___|_|  |_.__/|___/\__|_|\__,_|_|  \__| \_/\_/ |_| |_| |_|     #
#                                                                             #
###############################################################################
# Initialise                                                                {{{
#------------------------------------------------------------------------------
hc() {
    herbstclient "$@"
}
hc emit_hook reload
#Max default
configdir="/home/david/.config/herbstluftwm"
themedir=$configdir/"themes"
paneldir=$configdir/"panels"
#bindir=$configdir/"bin"
# Clear dmenu cache, needed for nixos
rm ~/.cache/dmenu_run

hc lock
#hc spawn $bindir/dialoglistener
#Keybindings
hc keyunbind --all
$configdir/keybinds 

#theming
#$themedir/moontheme
$themedir/maintheme
#$themedir/papertheme
#$themedir/snowtheme
#$themedir/snowtheme


hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class='GLava' manage=off
#hc rule class='zoom' floating=on

hc detect_monitors
hc set default_frame_layout 1
# panel
# find the panel
nmon=$(herbstclient list_monitors | wc -l)
panel=$paneldir/dzen2/dzenpanel
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" "$monitor" &
done

if hc silent new_attr bool my_not_first_autostart ; then
	hc setenv theme light
	feh --bg-fill ~/Pictures/wallpapers/hank.jpg
	cp "$HOME/.config/termite/dayconf" "$HOME/.config/termite/config"
	flashfocus &
	# startup apps
	# run fancy glava thing
	if [ "$nmon" -gt 1  ]; then
		bash ~/.screenlayout/2_monitor.sh
		hc reload
		glava &
	fi
fi

hc unlock

# rules
hc unlock


#hc reload

#xset s off -dpms

